apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: namegenerator-ingress-api-minion
  namespace: apigw
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=apigw rewrite=/"
spec:
  rules:
    - host: www.name-generator.com
      http:
        paths:
        - path: /api/v1/
          backend:
             serviceName: apigw
             servicePort: 80
