apiVersion: extensions/v1beta1 
kind: Ingress 
metadata: 
  name: namegenerator-ingress-main 
  namespace: main 
  annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.org/mergeable-ingress-type: "master" 
spec: 
  rules: 
  - host: www.name-generator.com

---

apiVersion: extensions/v1beta1 
kind: Ingress 
metadata: 
  name: namegenerator-ingress-webapp-minion 
  namespace: webapp 
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion" 
spec: 
  rules:
    - host: www.name-generator.com
      http: 
        paths: 
        - path: /
          backend: 
             serviceName: frontend 
             servicePort: 80

---

apiVersion: extensions/v1beta1 
kind: Ingress 
metadata: 
  name: namegenerator-ingress-api-minion 
  namespace: apigw
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/rewrites: "serviceName=apigw-microapigw rewrite=/"
spec: 
  rules:
    - host: www.name-generator.com
      http: 
        paths: 
        - path: /api/v1/
          backend: 
             serviceName: apigw
             servicePort: 80

---


