apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: namegenerator-ingress-webapp-minion
  namespace: webapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: www.name-generator.com
      http:
        paths:
        - path: /
          backend:
             serviceName: frontend
             servicePort: 80
