---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: debug
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: registry.gitlab.com/k8sfch/demo-name-generator/frontend:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: debug
      imagePullSecrets:
        - name: regcred
